In [2]:
#Numpy = Numeric Python
#Numpy里面核心的内容是n维数组ndarray

In [3]:
import numpy as np

In [4]:
#创建n维数组
arr = np.array([1,23,3,4])

In [5]:
arr

array([ 1, 23,  3,  4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
#ndim属性，当前数组的维度
arr.ndim

2

In [9]:
#shape，当前数组的结构
arr.shape

(2, 4)

In [10]:
#size，当前数组中元素的个数
arr.size

8

In [14]:
#np.linspace(start,stop,num=50,endpoint=True),生成一个维的数组，从start开始到stop,共产生num个数，并且是等差的，默认包含stop，如果endpoint为False，那么不包含
lin = np.linspace(0,10,100)
lin

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [15]:
?np.linspace

In [16]:
m = np.fromfunction(lambda x:x*2, (10,))     
m

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [17]:
m = np.fromfunction(lambda x,y:(x+1)*(y+1), (9,9))
m

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [18]:
#随机数
#0-150之间产生3个随机整数
np.random.randint(0,150,3)

array([131,   0,  62])

In [20]:
np.random.randint(0,150,(2,3))

array([[133,  37,  54],
       [ 32,  50, 136]])

In [21]:
#按照指定维度产生随机数，符合正态分布
np.random.randn(2,3,4)

array([[[-1.50455845,  1.95334719,  0.06759455,  1.18423781],
        [-0.16892004,  0.62952258, -0.61815639, -1.93517269],
        [ 0.38024842, -0.25753178,  0.32932113,  0.35482586]],

       [[-0.98599223, -0.32019517,  1.03630653,  1.80833777],
        [ 1.07769702, -1.08887381, -0.43684002, -0.6514454 ],
        [-0.22415362, -0.9265865 , -0.78429757, -0.43200192]]])

In [22]:
#0-150之间产生3个随机数
np.random.uniform(0,150,3)

array([74.07111385, 50.63843516, 31.16204589])

In [23]:
#数组之间可以进行运算
arr = np.array([2,3,4])
arr

array([2, 3, 4])

In [24]:
arr + arr

array([4, 6, 8])

In [26]:
arr * 3

array([ 6,  9, 12])

In [27]:
#切片和索引
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
arr[5]

6

In [29]:
arr[0:4]

array([1, 2, 3, 4])

In [30]:
#n维数组中的切片属于引用切片
arr

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
arr2 = arr[1:4]
arr2

array([2, 3, 4])

In [32]:
arr2[0:3] = 1

In [33]:
arr2

array([1, 1, 1])

In [34]:
arr

array([1, 1, 1, 1, 5, 6, 7])

In [36]:
#arange,相当于是高级版本的range
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [38]:
#根据指定结构生成n维数组
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
#布尔索引
names = np.array(["Joe","Joe","Joe","Tina","Tina","Tim","Tim","Mecheal"])
names

array(['Joe', 'Joe', 'Joe', 'Tina', 'Tina', 'Tim', 'Tim', 'Mecheal'],
      dtype='<U7')

In [40]:
names=="Joe"

array([ True,  True,  True, False, False, False, False, False])

In [41]:
names[names=="Joe"]

array(['Joe', 'Joe', 'Joe'], dtype='<U7')

In [42]:
#sum求和函数
a = np.random.randint(1,10,(4,5))
a

array([[8, 3, 4, 5, 5],
       [8, 8, 1, 1, 4],
       [3, 8, 7, 1, 3],
       [1, 8, 8, 1, 1]])

In [43]:
np.sum(a)

88

In [44]:
#每一行数据的和
np.sum(a, axis=1)

array([25, 22, 22, 19])

In [45]:
np.sum(a, axis=0)


array([20, 27, 20,  8, 13])

In [46]:
#Pandas两个数据结构 Series,DataFrame
import pandas as pd
from pandas import Series, DataFrame

In [47]:
#Series可以看成是一个带有索引的数组
s = Series(["Joe","Tina","Tim","Mecheal","David"])
s

0        Joe
1       Tina
2        Tim
3    Mecheal
4      David
dtype: object

In [48]:
s = Series(["Joe","Tina","Tim","Mecheal","David"],index=[1,2,3,4,5])
s

1        Joe
2       Tina
3        Tim
4    Mecheal
5      David
dtype: object

In [49]:
#index索引
s.index

Int64Index([1, 2, 3, 4, 5], dtype='int64')

In [50]:
#values值
s.values

array(['Joe', 'Tina', 'Tim', 'Mecheal', 'David'], dtype=object)

In [51]:
path = "orders.tsv"
data = pd.read_csv(path, sep="\t")

In [53]:
#获取前五条数据
data.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [54]:
#获取后五条数据 
data.tail()

order_id  quantity           item_name  \
4617      1833         1       Steak Burrito   
4618      1833         1       Steak Burrito   
4619      1834         1  Chicken Salad Bowl   
4620      1834         1  Chicken Salad Bowl   
4621      1834         1  Chicken Salad Bowl   

                                     choice_description item_price  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

In [55]:
#结构
data.shape

(4622, 5)

In [56]:
#列
data.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [57]:
#数据集的信息，包含列名，数据类型，是否有空值
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 126.4+ KB


In [58]:
data["item_name"]

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
5                                Chicken Bowl
6                               Side of Chips
7                               Steak Burrito
8                            Steak Soft Tacos
9                               Steak Burrito
10                        Chips and Guacamole
11                       Chicken Crispy Tacos
12                         Chicken Soft Tacos
13                               Chicken Bowl
14                        Chips and Guacamole
15      Chips and Tomatillo-Green Chili Salsa
16                            Chicken Burrito
17                            Chicken Burrito
18                                Canned Soda
19                               Chicken Bowl
20                        Chips and Guacamole
21                           Barba

In [59]:
data.item_name

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
5                                Chicken Bowl
6                               Side of Chips
7                               Steak Burrito
8                            Steak Soft Tacos
9                               Steak Burrito
10                        Chips and Guacamole
11                       Chicken Crispy Tacos
12                         Chicken Soft Tacos
13                               Chicken Bowl
14                        Chips and Guacamole
15      Chips and Tomatillo-Green Chili Salsa
16                            Chicken Burrito
17                            Chicken Burrito
18                                Canned Soda
19                               Chicken Bowl
20                        Chips and Guacamole
21                           Barba

In [60]:
#当前数据集中出现次数最多的商品是什么？
data["item_name"].value_counts()

Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chicken Salad Bowl                       110
Chips and Fresh Tomato Salsa             110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Cr

In [62]:
#升序排列
data["item_name"].value_counts(ascending=True)

Carnitas Salad                             1
Veggie Crispy Tacos                        1
Chips and Mild Fresh Tomato Salsa          1
Crispy Tacos                               2
Bowl                                       2
Salad                                      2
Steak Salad                                4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Carnitas Crispy Tacos                      7
Veggie Soft Tacos                          7
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     11
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Chips and Roasted Chili Corn Salsa        22
Barbacoa Soft Tacos                       25
Nantucket Nectar                          27
Steak Sala

In [65]:
#一共有多少种商品被下单
data["item_name"].value_counts().shape[0]

50

In [66]:
data["item_name"].nunique()

50

In [67]:
data.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [70]:
#将数据集中的item_price进行转换，去除$，转换成浮点数
#apply，对指定的某一列进行处理，根据传入的参数处理，通常参数为一个函数
def str2float(x):
    #x-->"$2.39"-->2.39
    return float(x[1:])
    
#data["item_price"].apply(str2float)

data["item_price"] = data["item_price"].apply(lambda x : float(x[1:]))
data.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98

In [71]:
#计算当前数据集中，所有记录的总收入
data.item_price.sum()

34500.16

In [72]:
#当前数据集中一共有多少个订单
data.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98

In [75]:
data.order_id.value_counts().shape[0]

1834

In [76]:
data.order_id.nunique()

1834

In [77]:
data.order_id.value_counts().count()

1834

In [78]:
#计算当前数据集中订单的平均总价
#goupby根据某一列进行分组操作

data.groupby(["order_id"]).sum().mean()

quantity  item_price
order_id                      
1                4       11.56
2                2       16.98
3                2       12.67
4                2       21.00
5                2       13.70
6                2       17.50
7                2       15.70
8                2       10.88
9                3       10.67
10               2       13.20
11               2       12.38
12               2       14.37
13               2       10.88
14               2       10.08
15               2       10.88
16               2       10.68
17               2       10.08
18               4       24.90
19               2       13.90
20               4       36.20
21               3       23.36
22               2       12.98
23               3       11.17
24               2       12.07
25               2       11.38
26               2       20.50
27               2       13.90
28               4       33.70
29               2       17.98
30               3       23.36
...            ...         ...
1805             2       20.00
1806             4       13.00
1807             2       18.64
1808             2       13.70
1809             3       14.45
1810             2       23.00
1811             3       29.25
1812             4       22.50
1813             2       17.50
1814             2       13.70
1815             2       12.50
1816             2       13.20
1817             4       13.00
1818             2       18.14
1819             2       13.20
1820             2       12.50
1821             2       13.70
1822             4       23.00
1823             3       12.15
1824             3       26.95
1825             6       66.50
1826             4       15.95
1827             5       32.95
1828             3       14.45
1829             3       24.25
1830             2       23.00
1831             3       12.90
1832             2       13.20
1833             2       23.50
1834             3       28.75

[1834 rows x 2 columns]